name: Format

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rustup (apply rust-toolchain.toml)
        run: rustup show
      - name: Format
        run: cargo fmt -- --check
